create table "public"."posts" (
    "id" bigint generated by default as identity not null,
    "text" text,
    "created_at" timestamp with time zone default now()
);


alter table "public"."posts" enable row level security;

CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (id);

alter table "public"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";


