create table "public"."posts" (
    "id" bigint generated by default as identity not null,
    "title" text not null default ''::text,
    "text" text not null default ''::text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);

create extension if not exists moddatetime schema extensions;
create trigger handle_updated_at before update on posts 
for each row execute function extensions.moddatetime (updated_at);

alter table "public"."posts" enable row level security;

CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (id);

alter table "public"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";


